version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./server:/app
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
